---
profiles:
  plexnode:
    label: "Plex Media Server"
    prefix: "plex"
    allow_suffix: true
    primary_role: "PLEX"
    pool: "PRODUCTION"
  devnode:
    label: "Dev Machine"
    prefix: "dev"
    allow_suffix: true
    primary_role: "DEVELOPMENT"
    pool: "DEVELOPMENT"
