---
profiles:
  devnode:
    label: "Developer Node"
    prefix: "dev"
    allow_suffix: true
    primary_role: "DEVELOPMENT"
    pool: "DEVELOPMENT"
    requires_primary_role: true
    requires_pool: true
